AWSTemplateFormatVersion: 2010-09-09
Description: Wordpress Template
Parameters:
  InstanceType:
    Type: String
    Description: EC2 instances size
    Default: t2.micro
  ImageId:
    Type: String
    Description: EC2 instances image id
    Default: ami-00b8917ae86a424c9
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an EC2 KeyPair to enable SSH access to the instance
    Default: wordpress
  SshPort:
    Type: Number
    Description: SSH port
    Default: 22
    MinValue: 22
    MaxValue: 65535
  SourceCidr:
    Type: String
    Description: CIDR Block of IPv4 IP addresses allowed to access EC2 instances via SSH
    AllowedPattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(/([0-9]|[1-2][0-9]|3[0-2]))?$"
    ConstraintDescription: The value must be valid IPv4 CIDR block.
    Default: 0.0.0.0/32
  DBName:
    Type: String
    Default: wordpress
  DBUsername:
    Type: String
    Default: wordpress
  DBPassword:
    Type: String
    Default: wordpress
Resources:
  ############################ VPC ############################
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.16.0.0/24
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: wordpress-vpc
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: wordpress-igw
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  ############################ Database ############################
  DatabaseSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.16.0.32/27
      Tags:
        - Key: Name
          Value: wordpress-sn-database-a
  DatabaseSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.16.0.64/27
      Tags:
        - Key: Name
          Value: wordpress-sn-database-b
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: wordpress-sn-group
      DBSubnetGroupDescription: Database Subnet Group
      SubnetIds:
        - !Ref DatabaseSubnetA
        - !Ref DatabaseSubnetB
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    # DependsOn: WordpressSecurityGroup # TODO: DELETE?
    Properties:
      GroupDescription: Open database for application access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WordpressSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WordpressSecurityGroup
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: MySQL
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
  ############################ EC2 ############################
  WordpressRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: wordpress-rt-app
  WordpressRouteTableDefaultIPv4:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId:
        Ref: WordpressRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  WordpressRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref WordpressSubnet
      RouteTableId:
        Ref: WordpressRouteTable
  WordpressSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.16.0.0/27
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: wordpress-sn-app
  WordpressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: A Security Group for Wordpress VPC
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
        - CidrIp: 0.0.0.0/0
          FromPort: 8080
          ToPort: 8080
          IpProtocol: tcp
        - CidrIp: !Ref SourceCidr
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
  WordpressEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref WordpressSubnet
      SecurityGroupIds:
        - !Ref WordpressSecurityGroup
      KeyName: !Ref KeyPairName
      Tags:
        - Key: Name
          Value: wordpress-ec2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export DATABASE_NAME=${DBName}
          export DATABASE_USER=${DBUsername}
          export DATABASE_PASSWORD=${DBPassword}
          export DATABASE_HOST="${Database.Endpoint.Address}"
          sudo yum install -y httpd
          sudo service httpd start
          mkdir /home/ec2-user/wordpress-tar
          cd /home/ec2-user/wordpress-tar
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          cd /home/ec2-user/wordpress-tar/wordpress
          cp wp-config-sample.php wp-config.php
          sed "s/database_name_here/$DATABASE_NAME/g" -i wp-config.php
          sed "s/username_here/$DATABASE_USER/g" -i wp-config.php
          sed "s/password_here/$DATABASE_PASSWORD/g" -i wp-config.php
          sed "s/localhost/$DATABASE_HOST/g" -i wp-config.php
          sudo amazon-linux-extras install -y mariadb10.5 php8.2
          cd /home/ec2-user/wordpress-tar
          sudo cp -r wordpress/* /var/www/html/
          sudo service httpd restart
Outputs:
  WordpressIP:
    Description: Wordpress EC2 instance public IP
    Value: !GetAtt WordpressEC2Instance.PublicIp
